name: CI - Publish
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on:
  release:
    types: [created]
jobs:
  publish-npm:
    uses: ./.github/workflows/reusable-ci-publish.yml
    secrets:
      NPMAUTHTOKEN: ${{ secrets.NPMAUTHTOKEN }}
