name: CI - Publish
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on:
  push:
    tags:
      - '*'
jobs:
  publish-npm:
    uses: ./.github/workflows/reusable-ci-publish.yml
    secrets:
      NPMAUTHTOKEN: ${{ secrets.NPMAUTHTOKEN }}
