name: CI - Publish
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on:
  pull_request_target:
    branches: [main]
jobs:
  publish-npm:
    uses: ./.github/workflows/reusable-ci-publish.yml
    secrets:
      NPMAUTHTOKEN: ${{ secrets.NPMAUTHTOKEN }}
