name: CI - Publish
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on:
  workflow_call:
    secrets:
      NPMAUTHTOKEN:
        required: true
jobs:
  checking:
    - name: Check PR version
      shell: bash
      run: |
        pr="$(jq -r '.version' < ./package.json)"
        # get my latest version
        # modify this with your own style
        latest="$(git describe --tag --abbrev=0)"
        php -r 'if(version_compare("'"$pr"'","'"$latest"'",">")){exit(0);};exit(1);'
  publish-npm:
    needs: checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMAUTHTOKEN}}
  tag:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
