name: CI - Lint App
on:
  workflow_call:
    secrets:
      NPMAUTHTOKEN:
        required: true
jobs:
  lintApp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 14 ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Add NPM Token
        run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMAUTHTOKEN }}" > .npmrc'
      - name: Install modules
        run: yarn
      - name: Lint project
        run: yarn lint
