name: CI - Test App
on:
  workflow_call:
    secrets:
      NPMAUTHTOKEN:
        required: true
jobs:
  testApp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 14 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Node Version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}
    - name: Add NPM Token
      run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMAUTHTOKEN }}" > .npmrc'
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
