name: CI - Publish
run-name: "${{ github.workflow }} - ${{ github.ref_name }}"
on:
  workflow_call:
    secrets:
      NPMAUTHTOKEN:
        required: true
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version and tag
        run: |
          version=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$version" >> $GITHUB_ENV
          echo "LATEST_TAG=$(git describe --tag --abbrev=0 | cut -c 2-)" >> $GITHUB_ENV
      - name: PR version is invalid
        if: ${{ env.CURRENT_VERSION = env.LATEST_TAG }}
        run: |
          echo "Error: Same version found. Please update version in package.json"
          exit 1
  publish-npm:
    needs: checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMAUTHTOKEN}}
  tag:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
